# getting started with numpy

In [1]:
import numpy as np

arr = np.array([[0,1,2],[3,4,5],[6,7,8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [2]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [3]:
arr.cumsum(axis=1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]])

In [4]:
arr = np.random.randn(100)
arr

array([-0.00384373, -1.24637166, -0.51301415,  0.28585478,  0.68268786,
       -2.33459525, -0.54454978,  0.4260117 , -0.29831174,  1.04648665,
       -0.59946943, -1.35514485,  0.93982305,  1.28830511, -1.31705237,
       -0.52442936,  0.88525923, -0.30091451, -1.58718412, -0.42384922,
        2.64945528, -1.25954144, -0.92085024,  0.21414219,  0.76588703,
       -0.77194924, -0.99863146,  2.07582588, -1.75645094, -0.48082949,
       -3.30401379,  0.57089355,  1.03833452, -0.3722594 ,  0.20213557,
        1.58027241,  0.32964824, -2.09353174,  0.61825522, -1.18112546,
       -1.01497149,  0.62855205,  0.04570643,  0.42687335, -0.28752785,
       -0.55045981,  0.64765704,  0.36197286, -1.4516976 , -0.76905551,
       -0.61939243,  0.34555741, -0.77007726, -0.20140477, -2.31989591,
       -1.0387905 , -0.74987143, -0.39320133, -1.22218238, -0.45226935,
        1.22349116,  0.525285  ,  0.28823875,  0.33923998,  0.15185037,
       -0.35269774,  0.41975076,  0.72061663,  0.59354067, -0.16

In [5]:
(arr > 0).sum()

45

In [6]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [7]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.save('some_array.npy',arr)

In [9]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.savez('array_achive.npz',a=arr,b=arr)

In [11]:
arch = np.load('array_achive.npz')
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x = np.array([[1., 2., 3.], [4., 5., 6.]])
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [13]:
y.dot(x)

array([[ 98., 127., 156.],
       [ 27.,  33.,  39.],
       [ 44.,  61.,  78.]])

In [14]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [15]:
x @ np.ones(3)

array([ 6., 15.])

In [16]:
from numpy.linalg import inv, qr

X = np.random.randn(5,5)
X

array([[-0.09027367,  1.11577168,  0.2888058 ,  0.83008279,  1.10506749],
       [ 0.41460686,  0.43984418, -0.89481722,  0.54707984,  1.53171206],
       [-0.24967409,  0.86797564, -0.93439888,  0.59751646,  0.97507275],
       [-1.01309377,  2.24866789,  1.18175323, -1.7954873 , -0.60418311],
       [ 0.28638896,  0.98151704, -0.67046114,  0.91146868,  1.58801688]])

In [17]:
mat = X.T.dot(X)

In [18]:
mat

array([[ 1.35076296, -2.1320892 , -1.55301323,  2.08273562,  1.35873408],
       [-2.1320892 ,  8.21167401,  1.11692723, -1.45739012,  2.95311551],
       [-1.55301323,  1.11692723,  3.60326674, -3.54104968, -3.74125825],
       [ 2.08273562, -1.45739012, -3.54104968,  5.39990952,  4.87011906],
       [ 1.35873408,  2.95311551, -3.74125825,  4.87011906,  7.40491772]])

In [19]:
inv(mat)

array([[ 34.59253214,  20.49854897,  -8.00731109,   9.05872493,
        -24.52574488],
       [ 20.49854897,  13.11752473,  -5.51458425,   6.4914749 ,
        -16.04817052],
       [ -8.00731109,  -5.51458425,   3.31008381,  -2.5715443 ,
          7.03216672],
       [  9.05872493,   6.4914749 ,  -2.5715443 ,   4.33256351,
         -8.39974018],
       [-24.52574488, -16.04817052,   7.03216672,  -8.39974018,
         20.11270872]])

In [20]:
mat.dot(inv(mat))

array([[ 1.00000000e+00,  4.25410313e-15,  3.44380948e-15,
        -6.68511587e-15, -4.04329237e-15],
       [ 7.05984561e-15,  1.00000000e+00, -4.66309149e-15,
         4.97999071e-15,  1.02204606e-14],
       [ 1.66991582e-14, -2.90549689e-15,  1.00000000e+00,
         1.38207037e-14, -8.15637748e-15],
       [-1.73434625e-15,  1.03521518e-14,  2.15520387e-15,
         1.00000000e+00, -1.40028480e-14],
       [-7.87187162e-15,  8.87723271e-15,  5.86783207e-15,
        -1.12239052e-14,  1.00000000e+00]])

In [21]:
samples = np.random.normal(12,3)

In [22]:
samples

11.967851934710495

In [23]:
samples = np.random.normal(size=(4,4))
samples

array([[-0.21308777,  0.66363693,  0.14250425,  0.18948651],
       [ 0.52491127,  0.07251253,  0.24332261,  0.40548375],
       [ 0.86567667, -0.2870272 ,  1.66281937,  0.09058309],
       [ 1.84689054,  1.40023642, -0.24651911,  0.95346807]])

In [24]:
from random import normalvariate

N = 100000

%timeit samples = [normalvariate(0,1) for _ in range(N)]

79.3 ms ± 4.73 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [25]:
samples

array([[-0.21308777,  0.66363693,  0.14250425,  0.18948651],
       [ 0.52491127,  0.07251253,  0.24332261,  0.40548375],
       [ 0.86567667, -0.2870272 ,  1.66281937,  0.09058309],
       [ 1.84689054,  1.40023642, -0.24651911,  0.95346807]])

In [26]:
nsteps = 1000
draws = np.random.randint(0,2,size=nsteps)
draws

array([0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,

In [27]:
steps = np.where(draws > 0, 1, -1)

In [28]:
steps

array([-1, -1,  1, -1,  1,  1,  1, -1,  1, -1, -1,  1, -1,  1,  1,  1,  1,
       -1, -1,  1, -1, -1,  1, -1, -1,  1, -1, -1,  1, -1,  1,  1, -1,  1,
        1,  1,  1,  1,  1, -1, -1,  1,  1, -1,  1, -1,  1, -1, -1, -1,  1,
        1,  1,  1, -1,  1, -1,  1, -1, -1, -1,  1,  1,  1,  1, -1,  1, -1,
       -1, -1,  1, -1,  1, -1,  1, -1,  1, -1, -1, -1, -1,  1,  1,  1, -1,
        1,  1, -1, -1,  1,  1, -1, -1,  1,  1,  1, -1, -1, -1, -1,  1, -1,
        1,  1, -1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,
       -1, -1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1, -1,  1, -1,
       -1,  1,  1, -1,  1, -1, -1,  1, -1, -1, -1,  1,  1,  1,  1,  1,  1,
        1, -1, -1, -1, -1, -1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1, -1,
       -1, -1, -1, -1,  1,  1,  1, -1, -1,  1, -1,  1, -1, -1, -1, -1,  1,
        1, -1, -1, -1,  1,  1, -1,  1,  1,  1,  1,  1,  1, -1,  1, -1,  1,
        1,  1, -1, -1, -1,  1,  1,  1,  1,  1, -1,  1,  1, -1,  1, -1, -1,
        1,  1, -1, -1,  1

In [29]:
walks = steps.cumsum()

In [30]:
walks

array([ -1,  -2,  -1,  -2,  -1,   0,   1,   0,   1,   0,  -1,   0,  -1,
         0,   1,   2,   3,   2,   1,   2,   1,   0,   1,   0,  -1,   0,
        -1,  -2,  -1,  -2,  -1,   0,  -1,   0,   1,   2,   3,   4,   5,
         4,   3,   4,   5,   4,   5,   4,   5,   4,   3,   2,   3,   4,
         5,   6,   5,   6,   5,   6,   5,   4,   3,   4,   5,   6,   7,
         6,   7,   6,   5,   4,   5,   4,   5,   4,   5,   4,   5,   4,
         3,   2,   1,   2,   3,   4,   3,   4,   5,   4,   3,   4,   5,
         4,   3,   4,   5,   6,   5,   4,   3,   2,   3,   2,   3,   4,
         3,   4,   5,   4,   5,   6,   7,   8,   9,  10,  11,  10,  11,
        12,  13,  12,  11,  12,  13,  12,  11,  10,   9,   8,   7,   6,
         5,   6,   5,   4,   5,   4,   3,   4,   5,   4,   5,   4,   3,
         4,   3,   2,   1,   2,   3,   4,   5,   6,   7,   8,   7,   6,
         5,   4,   3,   4,   5,   6,   7,   8,   9,  10,  11,  10,   9,
         8,   7,   6,   5,   4,   5,   6,   7,   6,   5,   6,   

In [31]:
walks.min()

-13

In [32]:
walks.max()

44

In [33]:
walks = 5000
nsteps = 1000

draws = np.random.randint(0,2,size=(walks,nsteps))
draws

array([[1, 0, 0, ..., 1, 0, 1],
       [0, 0, 0, ..., 1, 1, 1],
       [1, 0, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 0, ..., 0, 0, 1],
       [1, 1, 1, ..., 0, 1, 0],
       [0, 0, 1, ..., 1, 1, 1]])

In [34]:
steps = np.where(draws > 0, 1, -1)
steps

array([[ 1, -1, -1, ...,  1, -1,  1],
       [-1, -1, -1, ...,  1,  1,  1],
       [ 1, -1,  1, ..., -1, -1, -1],
       ...,
       [ 1,  1, -1, ..., -1, -1,  1],
       [ 1,  1,  1, ..., -1,  1, -1],
       [-1, -1,  1, ...,  1,  1,  1]])

In [35]:
walks = steps.cumsum(1)

In [36]:
walks

array([[  1,   0,  -1, ..., -42, -43, -42],
       [ -1,  -2,  -3, ...,   2,   3,   4],
       [  1,   0,   1, ...,  -8,  -9, -10],
       ...,
       [  1,   2,   1, ...,   8,   7,   8],
       [  1,   2,   3, ...,  30,  31,  30],
       [ -1,  -2,  -1, ...,  42,  43,  44]])

In [37]:
talks = steps.cumsum()

In [38]:
talks

array([    1,     0,    -1, ..., -1832, -1831, -1830])

In [39]:
(np.abs(walks) >= 10).argmax()

217

In [40]:
hit30 = (np.abs(walks) >= 30).any()

In [41]:
hit30

True

In [42]:
hit301 = (np.abs(walks) >= 30).any(1)
hit301

array([ True, False, False, ..., False,  True,  True])

In [43]:
len(hit301)

5000

In [44]:
walks.shape

(5000, 1000)

In [45]:
arr = np.arange(12)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [47]:
arr1 = np.reshape(arr,(4,3))
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

# getting started with pandas

In [48]:
import pandas as pd

In [49]:
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [50]:
obj.values

array([ 4,  7, -5,  3])

In [51]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [52]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [53]:
obj2['a']

-5

In [54]:
obj2[['c','a','d']]

c    3
a   -5
d    4
dtype: int64

In [55]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [56]:
obj2 * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [57]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [58]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [59]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [60]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [61]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [62]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [63]:
frame2 = pd.DataFrame(data,columns=['year','state','pop','debt'],
                     index =['one','two','three','four','five','six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [64]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [65]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [66]:
 frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [67]:
frame['debt'] = 16.5

In [68]:
frame2['debt'] = 16.5

In [69]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [70]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [71]:
val = pd.Series([-1.2,-1.5,-1.7], index=['two','four','five'])
frame2['debt'] = val

In [72]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [73]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [74]:
del frame2['eastern']

In [75]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [76]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [77]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
        'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [78]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [79]:
pd.DataFrame(pop,index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [80]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [81]:
 data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                index=['Ohio', 'Colorado', 'Utah', 'New York'],
                columns=['one', 'two', 'three', 'four'])

In [82]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [83]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [84]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [85]:
data.drop('two',axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [86]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [87]:
obj['b']

1.0

In [88]:
obj[1]

1.0

In [89]:
len(obj)

4

In [90]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [91]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [92]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [93]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [94]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                index=['Ohio', 'Colorado', 'Utah', 'New York'],
                columns=['one', 'two', 'three', 'four'])

In [95]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [96]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [97]:
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int64

In [98]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [99]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [100]:
data.loc[:'Utah']

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11

In [101]:
data.loc[:'Utah','two']

Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int64

In [102]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

In [103]:
data['three']

Ohio         2
Colorado     6
Utah        10
New York    14
Name: three, dtype: int64

In [104]:
data.loc[:,'three']

Ohio         2
Colorado     6
Utah        10
New York    14
Name: three, dtype: int64

In [105]:
data.loc['Utah','two']

9

In [106]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [107]:
ser2[-1]

2.0

In [108]:
ser2.loc[:'c']

a    0.0
b    1.0
c    2.0
dtype: float64

In [109]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],index=['a', 'c', 'e', 'f', 'g'])

In [110]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [111]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [112]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [113]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [114]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [115]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [116]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [117]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),columns=list('abcde'))

In [118]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [119]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [120]:
df2.loc[1,'b'] = np.nan
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [121]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [122]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [123]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [124]:
df2.add(df1, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [125]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [126]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [127]:
df1.radd(1)

a     b     c     d
0  1.0   2.0   3.0   4.0
1  5.0   6.0   7.0   8.0
2  9.0  10.0  11.0  12.0

In [128]:
arr = np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [129]:
arr[0]

array([0., 1., 2., 3.])

In [130]:
 arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [131]:
arr - arr[1]

array([[-4., -4., -4., -4.],
       [ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.]])

In [132]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [133]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),columns=list('bde'),index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [134]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [135]:
frame -  series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [136]:
series2 = pd.Series(range(3),index=['b','e','f'])
series2

b    0
e    1
f    2
dtype: int64

In [137]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [138]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [139]:
frame.sub(series3,axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [140]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [141]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah    1.827844 -2.026607  1.336550
Ohio   -0.150980 -0.461298  0.302722
Texas   0.141085  0.855137 -0.394575
Oregon  1.557132  0.201684 -1.881534

In [142]:
np.abs(frame)

b         d         e
Utah    1.827844  2.026607  1.336550
Ohio    0.150980  0.461298  0.302722
Texas   0.141085  0.855137  0.394575
Oregon  1.557132  0.201684  1.881534

In [143]:
1.246435 -- 0.555730

1.802165

In [144]:
f = lambda x: x.max() - x.min()
frame.apply(f)

b    1.978824
d    2.881744
e    3.218084
dtype: float64

In [145]:
frame.apply(f, axis='columns')

Utah      3.854451
Ohio      0.764020
Texas     1.249712
Oregon    3.438666
dtype: float64

In [146]:
def f(x):
    return pd.Series([x.min(),x.max()],index=['min','max'])

frame.apply(f)

b         d         e
min -0.150980 -2.026607 -1.881534
max  1.827844  0.855137  1.336550

In [147]:
format = lambda x : f'{x:.2f}'
frame.applymap(format)

b      d      e
Utah     1.83  -2.03   1.34
Ohio    -0.15  -0.46   0.30
Texas    0.14   0.86  -0.39
Oregon   1.56   0.20  -1.88

In [148]:
frame['e'].map(format)

Utah       1.34
Ohio       0.30
Texas     -0.39
Oregon    -1.88
Name: e, dtype: object

In [149]:
obj = pd.Series(range(4),index=['d','a','b','c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [150]:
frame.sort_index(axis=1)

b         d         e
Utah    1.827844 -2.026607  1.336550
Ohio   -0.150980 -0.461298  0.302722
Texas   0.141085  0.855137 -0.394575
Oregon  1.557132  0.201684 -1.881534

In [151]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),index=['three', 'one'],columns=['d', 'a', 'b', 'c'])
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [152]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [153]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [154]:
frame.sort_index(axis=1,ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [155]:
obj = pd.Series([4,7,-3,2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [156]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [157]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [158]:
obj = pd.Series([7,-5,7,4,2,0,4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [159]:
frame.sort_values(by=['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [160]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [161]:
obj.sort_values()

1   -5
5    0
4    2
3    4
6    4
0    7
2    7
dtype: int64

In [162]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [163]:
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [165]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                        'c': [-2, 5, 8, -2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [166]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [167]:
obj = pd.Series(range(5),index=['a','a','b','b','c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [168]:
obj.index.is_unique

False

In [169]:
obj['c']

4

In [170]:
obj['a']

a    0
a    1
dtype: int64

In [171]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
df

0         1         2
a  0.118628  0.090192  1.214840
a -0.161647  0.388097  0.681461
b  0.227175  0.689262 -1.211691
b -1.134189 -0.266821 -0.718852

In [172]:
df.loc['b']

0         1         2
b  0.227175  0.689262 -1.211691
b -1.134189 -0.266821 -0.718852

In [173]:
df = pd.DataFrame([[1.4,np.nan],[7.1,-4.5],
                  [np.nan,np.nan],[0.75,-1.3]],
                 index=['a','b','c','b'],
                 columns=['one','two'])

df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
b  0.75 -1.3

In [174]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [175]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
b   -0.55
dtype: float64

In [176]:
df.mean(axis='columns',skipna=False)

a      NaN
b    1.300
c      NaN
b   -0.275
dtype: float64

In [177]:
df.idxmax()

one    b
two    b
dtype: object

In [178]:
df.idxmin()

one    b
two    b
dtype: object

In [179]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
b  9.25 -5.8

In [180]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [181]:
obj.describe()

count    5.000000
mean     2.000000
std      1.581139
min      0.000000
25%      1.000000
50%      2.000000
75%      3.000000
max      4.000000
dtype: float64

In [184]:
import pandas_datareader.data as web
all_data = {ticker: web.get_data_yahoo(ticker) for ticker in ['AAPL','IBM','MSFT','GOOG']}

TypeError: string indices must be integers